package com.czcode.projectservice.common.error;

public final class ProjectErrorCodes {

  private ProjectErrorCodes() {
  }

  public static final String VALIDATION_FAILED = "VALIDATION_FAILED";
  public static final String REQUEST_BODY_INVALID = "REQUEST_BODY_INVALID";
  public static final String BAD_REQUEST = "BAD_REQUEST";
  public static final String UNAUTHORIZED = "UNAUTHORIZED";
  public static final String FORBIDDEN = "FORBIDDEN";
  public static final String NOT_FOUND = "NOT_FOUND";
  public static final String CONFLICT = "CONFLICT";
  public static final String LOCKED = "LOCKED";
  public static final String RATE_LIMITED = "RATE_LIMITED";
  public static final String INTERNAL_ERROR = "INTERNAL_ERROR";

  public static final String PROJECT_OWNER_MISMATCH = "PROJECT_OWNER_MISMATCH";
  public static final String PROJECT_KEY_EXISTS = "PROJECT_KEY_EXISTS";
  public static final String PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND";
  public static final String PROJECT_ACCESS_DENIED = "PROJECT_ACCESS_DENIED";
  public static final String PROJECT_PERMISSION_DENIED = "PROJECT_PERMISSION_DENIED";
  public static final String PROJECT_MEMBER_NOT_FOUND = "PROJECT_MEMBER_NOT_FOUND";
  public static final String PROJECT_OWNER_TRANSFER_INVALID_TARGET = "PROJECT_OWNER_TRANSFER_INVALID_TARGET";
  public static final String PROJECT_OWNER_ALREADY_OWNER = "PROJECT_OWNER_ALREADY_OWNER";
  public static final String PROJECT_MEMBER_ROLE_GRANT_FORBIDDEN = "PROJECT_MEMBER_ROLE_GRANT_FORBIDDEN";
  public static final String PROJECT_MEMBER_OWNER_REMOVE_FORBIDDEN = "PROJECT_MEMBER_OWNER_REMOVE_FORBIDDEN";
  public static final String PROJECT_INVITATION_PENDING_EXISTS = "PROJECT_INVITATION_PENDING_EXISTS";
  public static final String PROJECT_INVITATION_NOT_FOUND = "PROJECT_INVITATION_NOT_FOUND";
  public static final String PROJECT_INVITATION_NOT_PENDING = "PROJECT_INVITATION_NOT_PENDING";
  public static final String PROJECT_INVITATION_EXPIRED = "PROJECT_INVITATION_EXPIRED";
  public static final String PROJECT_INVITATION_EMAIL_MISMATCH = "PROJECT_INVITATION_EMAIL_MISMATCH";
  public static final String PROJECT_INVITATION_OWNER_ACCEPT_FORBIDDEN = "PROJECT_INVITATION_OWNER_ACCEPT_FORBIDDEN";
  public static final String PROJECT_IDEMPOTENCY_CONFLICT = "PROJECT_IDEMPOTENCY_CONFLICT";
  public static final String PROJECT_BRANCH_NOT_FOUND = "PROJECT_BRANCH_NOT_FOUND";
  public static final String PROJECT_BRANCH_NAME_EXISTS = "PROJECT_BRANCH_NAME_EXISTS";
  public static final String PROJECT_BRANCH_INVALID_STATE = "PROJECT_BRANCH_INVALID_STATE";
  public static final String PROJECT_BRANCH_PROTECTED = "PROJECT_BRANCH_PROTECTED";
  public static final String PROJECT_BRANCH_PROTECTION_RULE_NOT_FOUND = "PROJECT_BRANCH_PROTECTION_RULE_NOT_FOUND";
  public static final String PROJECT_BRANCH_PROTECTION_RULE_EXISTS = "PROJECT_BRANCH_PROTECTION_RULE_EXISTS";
  public static final String PROJECT_CHECKPOINT_NOT_FOUND = "PROJECT_CHECKPOINT_NOT_FOUND";
  public static final String PROJECT_PUBLISH_RECORD_NOT_FOUND = "PROJECT_PUBLISH_RECORD_NOT_FOUND";
  public static final String PROJECT_PUBLISH_INVALID_REQUEST = "PROJECT_PUBLISH_INVALID_REQUEST";
  public static final String PROJECT_FILE_NODE_NOT_FOUND = "PROJECT_FILE_NODE_NOT_FOUND";
  public static final String PROJECT_FILE_PATH_EXISTS = "PROJECT_FILE_PATH_EXISTS";
}
